gst/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url

urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', include('login.urls')),

]

login/urls.py
from django.contrib import admin
from django.urls import path,include
from . import views
app_name = 'login'
urlpatterns = [
    path('index/', views.index, name='index'),
    path('', views.homepage, name='homepage'),
    path('about/', views.about, name='about'),
    path('login1/', views.login1, name='login1'),
    path('R1afill/<slug:gstin>/', views.R1afill, name='R1afill'),
    path('choice/<slug:gstin>/', views.choice, name='choice'),
    path('R2afill/<slug:gstin>', views.R2afill, name='R2afill'),
    path('B3afill/<slug:gstin>', views.B3afill, name='B3afill'),
    path('clogin/', views.clogin, name='directlogin'),
    path('status/', views.status, name='status'),

]

login/models.py
from django.db import models
# from phone_field import PhoneField

# Create your models here.
# class Animal(models.Model):
#	name=models.CharField(max_length=10,primary_key=True)
#	age=models.IntegerField()
# spouse=models.ForeignKeyField(animal)
class Client(models.Model):
    gstin = models.CharField(max_length=15, primary_key=True, unique=True)
    name = models.CharField(max_length=20)
    phn = models.CharField(max_length=11)
    usr = models.CharField(max_length=10)
    passwd = models.CharField(max_length=15)
    mail = models.CharField(max_length=15)
    pan = models.CharField(max_length=15)
    provisional_id = models.CharField(max_length=15)

class R1a(models.Model):
    gstin = models.ForeignKey(Client, on_delete=models.CASCADE)
   # gstinb = models.CharField(max_length=15)
    month = models.CharField(max_length=8)
   # invoice_no = models.IntegerField()
   # cust_name = models.CharField(max_length=20)
   # state_of_supply = models.CharField(max_length=15)
   # invoice_date = models.DateField()
   # invoice_value = models.IntegerField()
   # tax_rate = models.IntegerField()
    taxable_value = models.IntegerField()
    cgst = models.IntegerField(null=True)
    sgst = models.IntegerField(null=True)
    igst = models.IntegerField(null=True)
    cess = models.IntegerField(null=True)
    total = models.IntegerField(null=True)


class R1b(models.Model):
    gstin = models.ForeignKey(Client, on_delete=models.CASCADE)
    #gstinb = models.CharField(max_length=15, )
    month = models.CharField(max_length=20)
    nil_supply_is = models.IntegerField(null=True)
    nil_supply_ws = models.IntegerField(null=True)
    non_gst_is = models.IntegerField(null=True)
    non_gst_ws = models.IntegerField(null=True)
    other_exempted_is = models.IntegerField(null=True)
    other_exempted_ws = models.IntegerField(null=True)
    total = models.IntegerField(null=True)


class Client_extra(models.Model):
    gstin = models.ForeignKey(Client, on_delete=models.CASCADE)
    house_no = models.CharField(max_length=20)
    street = models.CharField(max_length=20)
    area = models.CharField(max_length=20)
    city = models.CharField(max_length=20)
    district = models.CharField(max_length=20)
    pincode = models.IntegerField()
    adhaar = models.CharField(max_length=20)


class B3a(models.Model):
    gstin = models.ForeignKey(Client, on_delete=models.CASCADE)
    month = models.CharField(max_length=20)
    #state = models.CharField(max_length=20)
    ty = models.CharField(max_length=3)
    taxable_value = models.IntegerField()
    total = models.IntegerField()
    igst = models.IntegerField()



class R2a(models.Model):
    gstin = models.ForeignKey(Client, on_delete=models.CASCADE)
    #intyper2a = models.CharField(max_length=4)
    #invoice_no = models.IntegerField()
    #invoice_date = models.DateField
    #invoice_value = models.IntegerField()
    #tax_rate = models.IntegerField()
    taxable_value = models.IntegerField()
    total = models.IntegerField()
    igst = models.IntegerField(null=True)
    cgst = models.IntegerField(null=True)
    sgst = models.IntegerField(null=True)
    cess = models.IntegerField(null=True)
    month = models.CharField(max_length=20)


class B3b(models.Model):
    gstin = models.ForeignKey(Client, on_delete=models.CASCADE)
    #intypeb3b = models.CharField(max_length=4)
    taxable_value = models.IntegerField()
    igst = models.IntegerField(null=True)
    cgst = models.IntegerField(null=True)
    sgst = models.IntegerField(null=True)
    cess = models.IntegerField(null=True)
    month = models.CharField(max_length=20)
    ty = models.CharField(max_length=3)
    total = models.IntegerField()

login/forms.py
from django.forms import ModelForm, forms
from .models import Client, R1a


class ClientEntry(ModelForm):

	class Meta:
		model=Client
		fields='__all__'
		allgstin = forms.ModelChoiceField(queryset=Client.objects.raw('SELECT * from Client'))



		

login/views.py
from django.shortcuts import render, redirect
from .models import Client, R1a, R2a, B3a
from django.template import RequestContext
from django.forms import ModelForm, forms
from django.db.models import signals
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.db import connection, transaction
#from .forms import ClientEntry

# Create your views here.
def homepage(request):
    if request.method=="GET":
        return render(request, "homepage.html")
    if request.method == "POST":
        return render(request, 'homepage.html')

def about(request):
    if request.method == "GET":
        return render(request, "about.html")

def login1(request):
    if request.method == "GET":
        return render(request, "login1.html")
    if request.method == "POST":
        return render(request, "index.html")


def index(request):
    if request.method == "POST":
        request_context = RequestContext(request)
        data = Client()
        data.name = request.POST.get('name')
        data.gstin = request.POST.get('gstin')
        data.phn = request.POST.get('phn')
        data.usr = request.POST.get('usr')
        data.passwd = request.POST.get('passwd')
        data.mail = request.POST.get('mail')
        data.pan = request.POST.get('pan')
        data.provisional_id = request.POST.get('provisional_id')
        data.save()

        return redirect('login:choice', gstin=str(data.gstin))
    if request.method == "GET":
        return render(request, 'index.html')

    def clean_username(self, gstin):
        user_model = get_user_model()  # your way of getting the User
        try:
            user_model.objects.get(username__iexact=gstin)
        except user_model.DoesNotExist:
            return gstin
        raise forms.ValidationError(_("This username has already existed."))

def clogin(request):
    if request.method =="POST":
        gstinl = request.POST.get('gstinl')
        return redirect('login:choice', gstin=str(gstinl))
    if request.method == "GET":
        return render(request, 'index.html')

def R1afill(request, gstin):
    if request.method == "POST":
            data = R1a()
            client = Client()
            client.gstin = gstin
            data.gstin = client
            data.igst = request.POST.get('igst')
            data.cess = request.POST.get('cess')
            data.month = request.POST.get('month')
            data.sgst = request.POST.get('sgst')
            data.taxable_value = request.POST.get('taxable_value')
            data.cgst = request.POST.get('cgst')
            data.igst=request.POST.get('igst')
            data.total = request.POST.get('total')
            data.save()
            client.save()
            return render(request, 'R1afill.html', context={'allgstin': gstin})
    if request.method == "GET":
        #return HttpResponseRedirect(reverse('login:R1afill', args=(gstin)))
        return render(request, 'R1afill.html', context={'allgstin': gstin})

def choice(request, gstin):
    if request.method == "GET":
        return render(request, 'choice.html', context={'allgstin': gstin})

    if request.method == "POST":
        return render(request, 'choice.html', context={'allgstin': gstin})

def R2afill(request, gstin):
    if request.method == "POST":
        r2a = R2a()
        r2 = Client()
        r2.gstin = gstin
        r2a.gstin = r2
        r2a.igst = request.POST.get('igst')
        r2a.sgst = request.POST.get('sgst')
        r2a.cgst = request.POST.get('cgst')
        r2a.month = request.POST.get('month')
        r2a.cess = request.POST.get('cess')
        r2a.taxable_value=request.POST.get('taxable_value')
        r2a.total = request.POST.get('total')
        r2.save()
        r2a.save()

        return render(request, 'R2afill.html', context={'allgstin': gstin})
    if request.method == "GET":
        return render(request, 'R2afill.html', context={'allgstin': gstin})

def B3afill(request, gstin):
    if request.method == "POST":
        r3 = Client()
        b3a = B3a()
        r3.gstin = gstin
        b3a.gstin = r3
        b3a.ty = request.POST.get('ty')
        b3a.month = request.POST.get('month')
        b3a.taxable_value = request.POST.get('taxable_value')
        b3a.total = request.POST.get('total')
        b3a.igst = request.POST.get('igst')
        r3.save()
        b3a.save()

        return render(request, 'B3afill.html', context={'allgstin': gstin})
    if request.method == "GET":
        return render(request, 'B3afill.html', context={'allgstin': gstin})

def status(request):
    if request.method == "POST":
        gst = request.POST.get('gstin')
        allclients = Client.objects.raw('select * from login_client')
        r1a = R1a.objects.filter(gstin=gst)
        r2a = R2a.objects.filter(gstin=gst)
        b3a = B3a.objects.filter(gstin=gst)
        return render(request, 'status.html', context={'allclients': allclients, 'r1a': r1a, 'r2a': r2a, 'b3a': b3a})
    if request.method == "GET":
        allclients = Client.objects.raw('select * from login_client')
        return render(request, 'status.html', context={'allclients': allclients})

login/templates/R1a.html
<html lang="en-us" class="gr__127_0_0_1">
    <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">{% load static %}
<title>Add r1a</title>
        <center><h1><strong>R1 form</strong></h1></center>
<link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'forms.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'fonts.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'widgets.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'responsive.css' %}"> 
    </head>
<body>
    <div>
    <nav class="navbar-goggles container-flex">
    <div id="navbar-left" class="container-flex">
      <div class="navbar-logo-container">
      </div>
    </div>

    <div id="navbar-right" class="container-flex">
      <div id="navbar-login">
        <div id="navbar-login-inner">

        

        

        

        <span class="status placeholder">
          <div id="navbar-anonymous">
          </div>
        </span></div>
    
  </div></div></nav>
    </div>
    <div id="content-main">



<form action="" method="POST" id="r1a_form">{% csrf_token %}
<div>







  <fieldset class="module aligned ">
    
        <div class="form-row field-month">
            
            
                <div>
                    
                    
                       <!-- <label class="required" for="id_month">Month:</label>
                        
                            <input type="text" name="month" class="vTextField" maxlength="8" required="" id="id_month">-->
                    <label class="required">month</label> <select name="month" required="" id="id_month">
    <option value="april">april</option>
    <option value="may">may</option>
    <option value="june">june</option>
     <option value="july">july</option>
     <option value="august">august</option>
     <option value="september">september</option>
     <option value="october">october</option>
     <option value="november">november</option>
     <option value="december">december</option>
     <option value="january">january</option>
     <option value="february">february</option>
    <option value="march">march</option>

</select>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-taxable_value">
            
            
                <div>
                    
                    
                        <label class="required" for="id_taxable_value">Taxable value:</label>
                        
                            <input type="number" name="taxable_value" class="vIntegerField" required="" id="id_taxable_value">
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-cgst">
            
            
                <div>
                    
                    
                        <label class="required" for="id_cgst">Cgst:</label>
                        
                            <input type="number" name="cgst" class="vIntegerField" required="" id="id_cgst">
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-sgst">
            
            
                <div>
                    
                    
                        <label class="required" for="id_sgst">Sgst:</label>
                        
                            <input type="number" name="sgst" class="vIntegerField" id="id_sgst">
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-igst">
            
            
                <div>
                    
                    
                        <label class="required" for="id_igst">Igst:</label>
                        
                            <input type="number" name="igst" class="vIntegerField" required="" id="id_igst">
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-cess">
            
            
                <div>
                    
                    
                        <label class="required" for="id_cess">Cess:</label>
                        
                            <input type="number" name="cess" class="vIntegerField" required="" id="id_cess">
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-total">
            
            
                <div>
                    
                    
                        <label class="required" for="id_total">Total:</label>
                        
                            <input type="number" name="total" class="vIntegerField" required="" id="id_total">
                        
                    
                    
                </div>
            
        </div>
    
</fieldset>













<div class="submit-row">

<input type="submit" value="Save" class="" name="_save"><br><br>

    <a href="{% url 'login:R2afill' allgstin %}"><b><strong>take to R2</strong></b></a>

<!--<input type="submit" value="Save and add another" name="_addanother">
<input type="submit" value="Save and continue editing" name="_continue">-->


</div>

    </div>
</form></div>
    <a href="{% url 'login:index' %}">back</a>
    </body>
</html>

login/templates/R1afill.html
<html lang="en-us" class="gr__127_0_0_1">
    <head><meta http-equiv="Content-Type" content="text/html; charset=UTF-8">{% load static %}
<title>Add r1a</title>
        <center><h1><strong>R1 form</strong></h1></center>
<link rel="stylesheet" type="text/css" href="{% static 'base.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'forms.css' %}">
<link rel="stylesheet" type="text/css" href="{% static 'fonts.css' %}">
   <link rel="stylesheet" type="text/css" href="{% static 'widgets.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'responsive.css' %}"> 
    </head>
<body>
    <div>
    <nav class="navbar-goggles container-flex">
    <div id="navbar-left" class="container-flex">
      <div class="navbar-logo-container">
      </div>
    </div>

    <div id="navbar-right" class="container-flex">
      <div id="navbar-login">
        <div id="navbar-login-inner">

        

        

        

        <span class="status placeholder">
          <div id="navbar-anonymous">
          </div>
        </span></div>
    
  </div></div></nav>
    </div>
    <div id="content-main">



<form action="" method="POST" id="r1a_form">{% csrf_token %}
<div>







  <fieldset class="module aligned ">
    
        <div class="form-row field-month">
            
            
                <div>
                    
                    
                       <!-- <label class="required" for="id_month">Month:</label>
                        
                            <input type="text" name="month" class="vTextField" maxlength="8" required="" id="id_month">-->
                    <label class="required">month</label> <select name="month" required="" id="id_month">
    <option value="april">april</option>
    <option value="may">may</option>
    <option value="june">june</option>
     <option value="july">july</option>
     <option value="august">august</option>
     <option value="september">september</option>
     <option value="october">october</option>
     <option value="november">november</option>
     <option value="december">december</option>
     <option value="january">january</option>
     <option value="february">february</option>
    <option value="march">march</option>

</select>
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-taxable_value">
            
            
                <div>
                    
                    
                        <label class="required" for="id_taxable_value">Taxable value:</label>
                        
                            <input type="number" name="taxable_value" class="vIntegerField" required="" id="id_taxable_value">
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-cgst">
            
            
                <div>
                    
                    
                        <label class="required" for="id_cgst">Cgst:</label>
                        
                            <input type="number" name="cgst" class="vIntegerField" required="" id="id_cgst">
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-sgst">
            
            
                <div>
                    
                    
                        <label class="required" for="id_sgst">Sgst:</label>
                        
                            <input type="number" name="sgst" class="vIntegerField" id="id_sgst">
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-igst">
            
            
                <div>
                    
                    
                        <label class="required" for="id_igst">Igst:</label>
                        
                            <input type="number" name="igst" class="vIntegerField" required="" id="id_igst">
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-cess">
            
            
                <div>
                    
                    
                        <label class="required" for="id_cess">Cess:</label>
                        
                            <input type="number" name="cess" class="vIntegerField" required="" id="id_cess">
                        
                    
                    
                </div>
            
        </div>
    
        <div class="form-row field-total">
            
            
                <div>
                    
                    
                        <label class="required" for="id_total">Total:</label>
                        
                            <input type="number" name="total" class="vIntegerField" required="" id="id_total">
                        
                    
                    
                </div>
            
        </div>
    
</fieldset>













<div class="submit-row">

<input type="submit" value="Save" class="" name="_save"><br><br>

    <a href="{% url 'login:R2afill' allgstin %}"><b><strong>take to R2</strong></b></a>

<!--<input type="submit" value="Save and add another" name="_addanother">
<input type="submit" value="Save and continue editing" name="_continue">-->


</div>

    </div>
</form></div>
    <a href="{% url 'login:index' %}">back</a>
    </body>
</html>

login/templates/choice.html
<!DOCTYPE html>
<html>
<head>
<style>
.button {
    background-color: #4CAF50;
    border: none;
    color: white;
    padding: 15px 25px;
    text-align: center;
    font-size: 16px;
    cursor: pointer;
}

.button:hover {
    background-color: blue;
}
</style>
</head>
<body>

<p> To fill GST-R1 please click on the button below</p>
    <a href="{% url 'login:R1afill' allgstin %}"><button class="button" type="button" >GST-R1 filling</button></a><br><br>

<p> To fill GST-R2 please click on the button below</p>
<!--<button class="button" onclick="location.href='R2a.html'" type="button" >GST-R2 filling</button><br><br>-->
     <a href="{% url 'login:R2afill' allgstin %}"><button class="button" type="button" >GST-R2 filling</button></a><br><br>

<p> To fill GST-3B please click on the button below</p>
<!--<button class="button" onclick="location.href='3b.html'" type="button" >GST-R3 filling</button><br><br>-->
     <a href="{% url 'login:B3afill' allgstin %}"><button class="button" type="button" >GST-R3 filling</button></a><br><br>



</body>
</html>

login/templates/homepage.html
<!DOCTYPE html>
<html>
<head>{% load static %}
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {
    
    font-family: "Lato", sans-serif;
}

.sidenav {
    height: 100%;
    width: 160px;
    position: fixed;
    z-index: 1;
    top: 0;
    left: 0;
    background-color: #111108;
    overflow-x: hidden;
    padding-top: 20px;
}

.sidenav a {
    padding: 6px 8px 6px 16px;
    text-decoration: none;
    font-size: 25px;
    color: #818181;
    display: block;
}

.sidenav a:hover {
    color: #f1f1f1;
}

.main {
    
    margin-left: 160px; /* Same as the width of the sidenav */
    font-size: 28px; /* Increased text to enable scrolling */
    padding: 0px 10px;
}

@media screen and (max-height: 450px) {
    .sidenav {padding-top: 15px;}
    .sidenav a {font-size: 18px;}
}
</style>
</head>
<body>

<div class="sidenav">
  <a href="{% url 'login:about' %}">About</a>
  <a href="{% url 'login:login1' %}">Login</a>
   
</div>

<div class="main">
    
  <center><h2>GST Client Management System</h2></center>
  <p>This website is for accessing and storing information about gst clients in a database and use the data for filling gst .</p>
  <img src="{% static "gstmodi.jpg" %}">
    </div>
     
</body>
</html> 

login/templates/index.html
<html>
    <head>{% load static %}

<link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
<style>
        p {
            color: red;
            
            text-align: left;
        } 
        </style>
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">

<!-- jQuery library -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>

<!-- Popper JS -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js"></script>

<!-- Latest compiled JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js"></script>
    </head>
<body>
<!--hello world
{% for a in animals%}
<li>{{a.name}}</li>
{%endfor%}-->
<strong>
     <form action="{% url 'login:directlogin' %}"  method="post">{% csrf_token %}
         <div class="form-group"><div class="card" style="width:50%">
             <h4 style="text-align: center;"><u>Existing Clients login</u></h4> 
             
        <p id="a"><label for="gstinl">GSTIN:</label> <input type="text" class="form-control" name="gstinl" maxlength="15" required="True" id="gstinl" autocomplete="off" placeholder="1234abc12345on1"></p>
             
        <div class="form-group">
        <button class="btn btn-success" type="submit" align="right" >Submit</button>
    </div></div></div>
    </form>
<div class="card" style="width:50%">
<h4 style="text-align: center;"><u>New Client Registration</u></h4>   
<form method="POST"> {% csrf_token %}
    <div class="form-group">
        <p id="b"><label for="id_gstin">GSTIN:</label> <input type="text" class="form-control" name="gstin" maxlength="15" required="True" id="id_gstin" autocomplete="off" placeholder="1234abc12345on1"></p>
    </div>
    <div class="form-group">
        <p><label for="id_name">NAME:</label> <input type="text" class="form-control" name="name" maxlength="20" required="" id="id_name"></p>
    </div>
    <div class="form-group">
        <p><label for="id_phn">PHONE NUMBER:</label> <input type="text" class="form-control" name="phn" maxlength="11" required="True" id="id_phn"></p>
    </div>
    <div class="form-group">
        <p><label for="id_usr">USER NAME:</label> <input type="text" class="form-control" name="usr" maxlength="10" required="" id="id_usr"></p>
    </div>
    <div class="form-group">
        <p><label for="id_passwd">PASSWORD:</label> <input type="text" class="form-control" name="passwd" maxlength="15" required="" id="id_passwd"></p>
    </div>
    <div class="form-group">
        <p><label for="id_mail">MAIL ID:</label> <input type="text" class="form-control" name="mail" maxlength="15" required="" id="id_mail"></p>
    </div>
    <div class="form-group">
        <p><label for="id_pan">PAN NUMBER:</label> <input type="text" class="form-control" name="pan" maxlength="15" required="" id="id_pan"></p>
    </div>
    
    <div class="form-group">
        <p><label for="id_provisional_id">PROVISIONAL ID:</label> <input type="text" name="provisional_id" class="form-control"  maxlength="15" required="" id="id_provisional_id"></p>
    </div>
    <div class="form-group">
        <button class="btn btn-success" type="submit" style="margin-left:auto;margin-right:auto;display:block;" value="Client" align="center" href="">Submit</button>
    </div>
</form>
    
   
</div>    
</strong>
</body>
</html>

login/templates/login1.html
<!DOCTYPE html>
<html>
<head>
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
body {font-family: Arial, Helvetica, sans-serif;}

/* Full-width input fields */
input[type=text], input[type=password] {
    width: 100%;
    padding: 12px 20px;
    margin: 8px 0;
    display: inline-block;
    border: 1px solid #ccc;
    box-sizing: border-box;
}

/* Set a style for all buttons */
button {
    background-color: #00FF00;
    color: white;
    padding: 14px 20px;
    margin: 8px 0;
    border: none;
    cursor: pointer;
    width: 100%;
}

button:hover {
    opacity: 0.8;
}

/* Extra styles for the cancel button */
.cancelbtn {
    width: auto;
    padding: 10px 18px;
    background-color: #f44336;
}

/* Center the image and position the close button */
.imgcontainer {
    text-align: center;
    margin: 24px 0 12px 0;
    position: relative;
}

img.avatar {
    width: 40%;
    border-radius: 50%;
}

.container {
    padding: 16px;
}

span.psw {
    float: right;
    padding-top: 16px;
}

/* The Modal (background) */
.modal {
    display: none; /* Hidden by default */
    position: fixed; /* Stay in place */
    z-index: 1; /* Sit on top */
    left: 0;
    top: 0;
    width: 100%; /* Full width */
    height: 100%; /* Full height */
    overflow: auto; /* Enable scroll if needed */
    background-color: rgb(0,0,0); /* Fallback color */
    background-color: rgba(0,0,0,0.4); /* Black w/ opacity */
    padding-top: 60px;
}

/* Modal Content/Box */
.modal-content {
    background-color: #fefefe;
    margin: 5% auto 15% auto; /* 5% from the top, 15% from the bottom and centered */
    border: 1px solid #888;
    width: 80%; /* Could be more or less, depending on screen size */
}

/* The Close Button (x) */
.close {
    position: absolute;
    right: 25px;
    top: 0;
    color: #000;
    font-size: 35px;
    font-weight: bold;
}

.close:hover,
.close:focus {
    color: red;
    cursor: pointer;
}

/* Add Zoom Animation */
.animate {
    -webkit-animation: animatezoom 0.6s;
    animation: animatezoom 0.6s
}

@-webkit-keyframes animatezoom {
    from {-webkit-transform: scale(0)} 
    to {-webkit-transform: scale(1)}
}
    
input[type=submit] {
  border: none; /*rewriting standard style, it is necessary to be able to change the size*/
  height: 50px;
  width: 70px;
}

@keyframes animatezoom {
    from {transform: scale(0)} 
    to {transform: scale(1)}
}

/* Change styles for span and cancel button on extra small screens */
@media screen and (max-width: 300px) {
    span.psw {
       display: block;
       float: none;
    }
    .cancelbtn {
       width: 100%;
    }
}
</style>
</head>
<body>

<center><h2>Auditor Login</h2></center>

<center><button onclick="document.getElementById('id01').style.display='block'" style="width:auto;">Login</button></center>

<div id="id01" class="modal">
  
  <form class="modal-content animate" action="{% url 'login:index' %}">{% csrf_token %}
    <div class="imgcontainer">
      <span onclick="document.getElementById('id01').style.display='none'" class="close" title="Close Modal">&times;</span>
      
    </div>

    <div class="container">
      <label for="uname"><b>Username</b></label>
      <input type="text" placeholder="Enter Username" name="uname" required>

      <label for="psw"><b>Password</b></label>
      <input type="password" placeholder="Enter Password" name="psw" required>
        
     <center><b> <input type="submit" size='' onclick="return check(this.form)" value="Login"> </b></center>
      
    </div>

    
  </form>
</div>

<!--<script>
// Get the modal
var modal = document.getElementById('id01');

// When the user clicks anywhere outside of the modal, close it
window.onclick = function(event) {
    if (event.target == modal) {
        modal.style.display = "none";
    }
}
</script> -->

<script language="javascript">
function check(form)
{

if(form.uname.value == "gaurav" && form.psw.value == "1234")
{
    return true;
}
else if(form.uname.value == "srivatsa" && form.psw.value == "6789")
{
    return true;
}
else
{
    alert("Error Password or Username")
    return false;
}
}
</script>

</body>
</html>